# Coleta de preços ajustados pelo Yahoo Finance

Nesta etapa, utilizamos o universo líquido construído a partir da COTAHIST da B3 para baixar os preços ajustados dos ativos pelo Yahoo Finance.

A COTAHIST foi usada para definir quais ações eram líquidas em cada janela histórica. Já o Yahoo Finance será usado para obter preços ajustados por eventos como dividendos, juros sobre capital próprio, desdobramentos e grupamentos.

In [1]:
from pathlib import Path

import pandas as pd
import yfinance as yf

In [2]:
PASTA_PROJETO = Path.cwd().parent
PASTA_DADOS_TRATADOS = PASTA_PROJETO / "dados_tratados"

universo_liquido = pd.read_csv(
    PASTA_DADOS_TRATADOS / "universo_liquido_por_janela.csv",
    parse_dates=[
        "inicio_formacao",
        "fim_formacao",
        "inicio_teste",
        "fim_teste"
    ]
)

universo_liquido.head()

  inicio_formacao fim_formacao inicio_teste  fim_teste  ativo
0      2010-01-04   2011-01-03   2011-01-04 2011-07-03  VALE5
1      2010-01-04   2011-01-03   2011-01-04 2011-07-03  PETR4
2      2010-01-04   2011-01-03   2011-01-04 2011-07-03  OGXP3
3      2010-01-04   2011-01-03   2011-01-04 2011-07-03  ITUB4
4      2010-01-04   2011-01-03   2011-01-04 2011-07-03  BVMF3

In [3]:
ativos_b3 = sorted(universo_liquido["ativo"].unique())

print(f"Quantidade de ativos únicos: {len(ativos_b3)}")
ativos_b3[:20]

Quantidade de ativos únicos: 248

['ABCB4',
 'ABEV3',
 'AEDU3',
 'AGEN11',
 'ALLL3',
 'ALOS3',
 'ALPA4',
 'ALSC3',
 'ALSO3',
 'ALUP11',
 'AMAR3',
 'AMBP3',
 'AMBV3',
 'AMBV4',
 'AMER3',
 'AMIL3',
 'ANIM3',
 'ARTR3',
 'ARZZ3',
 'ASAI3']

In [4]:
tickers_yahoo = [ativo + ".SA" for ativo in ativos_b3]

tickers_yahoo[:20]

['ABCB4.SA',
 'ABEV3.SA',
 'AEDU3.SA',
 'AGEN11.SA',
 'ALLL3.SA',
 'ALOS3.SA',
 'ALPA4.SA',
 'ALSC3.SA',
 'ALSO3.SA',
 'ALUP11.SA',
 'AMAR3.SA',
 'AMBP3.SA',
 'AMBV3.SA',
 'AMBV4.SA',
 'AMER3.SA',
 'AMIL3.SA',
 'ANIM3.SA',
 'ARTR3.SA',
 'ARZZ3.SA',
 'ASAI3.SA']

In [5]:
dados_yahoo = yf.download(
    tickers=tickers_yahoo,
    start="2010-01-01",
    end="2026-01-01",
    interval="1d",
    auto_adjust=True,
    group_by="column",
    threads=True,
    progress=True
)

$RRRP3.SA: possibly delisted; no timezone found
[                       0%                       ]$BVMF3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[*                      2%                       ]  6 of 248 completed$CESP6.SA: possibly delisted; no timezone found
$BRTO4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[*                      3%                       ]  7 of 248 completed$NTCO3.SA: possibly delisted; no timezone found
$ELET6.SA: possibly delisted; no timezone found
[***                    6%                       ]  14 of 248 completed$TBLE3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[***                    6%                       ]  15 of 248 completed$AMIL3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[***                    6%                       ]  16 of 248 completed$ARZZ3.SA: possibly delisted; no timezone found
$MNDL4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[***                    7%                       ]  17 of 248 completed$BRDT3.SA: possibly delisted; no timezone found
[***                    7%                       ]  18 of 248 completed$MILK11.SA: possibly delisted; no timezone found
$BPNM4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[****                   9%                       ]  22 of 248 completed$SMLE3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[******                12%                       ]  29 of 248 completed$ENBR3.SA: possibly delisted; no timezone found
[******                12%                       ]  30 of 248 completed$ECOD3.SA: possibly delisted; no timezone found
$TIET11.SA: possibly delisted; no timezone found
[******                13%                       ]  33 of 248 completed$BRIN3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[*******               14%                       ]  34 of 248 completed$GETI3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[*******               14%                       ]  35 of 248 completed$TCSL4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[*******               15%                       ]  38 of 248 completed$ESTC3.SA: possibly delisted; no timezone found
[********              16%                       ]  39 of 248 completed$MMXM3.SA: possibly delisted; no timezone found
[********              17%                       ]  43 of 248 completed$GUAR3.SA: possibly delisted; no timezone found
$STBP11.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[*********             18%                       ]  44 of 248 completed$ARTR3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[*********             18%                       ]  45 of 248 completed$FFTL4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[*********             19%                       ]  47 of 248 completed$SMLS3.SA: possibly delisted; no timezone found
[*********             19%                       ]  48 of 248 completed$LINX3.SA: possibly delisted; no timezone found
[**********            20%                       ]  49 of 248 completed$TMAR5.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
$TNLP3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[***********           22%                       ]  55 of 248 completed$BIDI11.SA: possibly delisted; no timezone found
[***********           23%                       ]  56 of 248 completed$PETZ3.SA: possibly delisted; no timezone found
[***********           23%                       ]  57 of 248 completed$AMBV3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[************          24%                       ]  59 of 248 completed$ELET3.SA: possibly delisted; no timezone found
[************          24%                       ]  60 of 248 completed$VIVO4.SA: possibly delisted; no timezone found
[************          25%                       ]  61 of 248 completed$GETI4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[*************         28%                       ]  69 of 248 completed$WIZS3.SA: possibly delisted; no timezone found
[*************         28%                       ]  70 of 248 completed$UGPA4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**************        29%                       ]  72 of 248 completed$PARD3.SA: possibly delisted; no timezone found
$GNDI3.SA: possibly delisted; no timezone found
[****************      33%                       ]  82 of 248 completed$CRUZ3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[****************      34%                       ]  84 of 248 completed$BRFS3.SA: possibly delisted; no timezone found
[****************      34%                       ]  85 of 248 completed$VIVT4.SA: possibly delisted; no timezone found
[*****************     36%                       ]  90 of 248 completed$CRFB3.SA: possibly delisted; no timezone found
[******************    37%                       ]  91 of 248 completed$CCRO3.SA: possibly delisted; no timezone found
[******************    37%                       ]  92 of 248 completed$PCAR5.SA: possibly delisted; no timezone found
[******************    37%                       ]  92 of 248 completed$BIDI4.SA: possibly delisted; no timezone found
$KROT11.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[******************    38%                       ]  95 of 248 completed$SULA11.SA: possibly delisted; no timezone found
[*******************   40%                       ]  98 of 248 completed$PCAR4.SA: possibly delisted; no timezone found
[********************  41%                       ]  102 of 248 completed$TRPL4.SA: possibly delisted; no timezone found
$ELPL3.SA: possibly delisted; no timezone found
[********************  42%                       ]  104 of 248 completed$LLXL3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[********************* 43%                       ]  106 of 248 completed$BBTG11.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************48%                       ]  120 of 248 completed$EMBR3.SA: possibly delisted; no timezone found
[**********************50%                       ]  123 of 248 completed$CTIP3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************50%                       ]  124 of 248 completed$VVAR3.SA: possibly delisted; no timezone found
[**********************50%                       ]  125 of 248 completed$VIIA3.SA: possibly delisted; no timezone found
[**********************54%*                      ]  133 of 248 completed$AZUL4.SA: possibly delisted; no timezone found
[**********************54%*                      ]  134 of 248 completed$CNTO3.SA: possibly delisted; no timezone found
[**********************54%*                      ]  135 of 248 completed$LCAM3.SA: possibly delisted; no timezone found
[**********************55%*                      ]  136 of 248 completed$MRFG3.SA: possibly delisted; no timezone found
$OHLB3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************55%*                      ]  137 of 248 completed$RUMO3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
$KROT3.SA: possibly delisted; no timezone found
[**********************58%***                    ]  145 of 248 completed$ALSC3.SA: possibly delisted; no timezone found
[**********************59%***                    ]  146 of 248 completed$ELPL6.SA: possibly delisted; no timezone found
[**********************60%****                   ]  148 of 248 completed$BBRK3.SA: possibly delisted; no timezone found
[**********************60%****                   ]  149 of 248 completed$RDCD3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************67%*******                ]  166 of 248 completed$SOMA3.SA: possibly delisted; no timezone found
[**********************67%*******                ]  167 of 248 completed$DTEX3.SA: possibly delisted; no timezone found
$DROG3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************68%********               ]  168 of 248 completed$ALLL3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************69%********               ]  170 of 248 completed$NETC4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************69%********               ]  172 of 248 completed$LAME4.SA: possibly delisted; no timezone found
[**********************71%*********              ]  175 of 248 completed$JBSS3.SA: possibly delisted; no timezone found
[**********************72%**********             ]  179 of 248 completed$TNLP4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************74%***********            ]  183 of 248 completed$QGEP3.SA: possibly delisted; no timezone found
[**********************74%***********            ]  184 of 248 completed$IGTA3.SA: possibly delisted; no timezone found
[**********************74%***********            ]  184 of 248 completed$IMCH3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************75%***********            ]  187 of 248 completed$BTOW3.SA: possibly delisted; no timezone found
[**********************76%***********            ]  189 of 248 completed$TAMM4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************77%************           ]  190 of 248 completed$ENAT3.SA: possibly delisted; no timezone found
[**********************77%************           ]  191 of 248 completed$TIMP3.SA: possibly delisted; no timezone found
$LAME3.SA: possibly delisted; no timezone found
[**********************78%************           ]  193 of 248 completed$AGEN11.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************81%**************         ]  202 of 248 completed$MPLU3.SA: possibly delisted; no timezone found
[**********************82%**************         ]  203 of 248 completed$BPAN4.SA: possibly delisted; no timezone found
[**********************82%**************         ]  204 of 248 completed$HRTP3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************83%***************        ]  205 of 248 completed$STBP3.SA: possibly delisted; no timezone found
[**********************83%***************        ]  206 of 248 completed$SUZB5.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
$TLPP4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************83%***************        ]  207 of 248 completed$ALSO3.SA: possibly delisted; no timezone found
[**********************85%****************       ]  210 of 248 completed$BRML3.SA: possibly delisted; no timezone found
[**********************89%******************     ]  220 of 248 completed$BKBR3.SA: possibly delisted; no timezone found
[**********************89%******************     ]  221 of 248 completed$MAGG3.SA: possibly delisted; no timezone found
[**********************90%******************     ]  222 of 248 completed$GOLL4.SA: possibly delisted; no timezone found
$MPXE3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************91%*******************    ]  225 of 248 completed$BISA3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[**********************96%*********************  ]  237 of 248 completed$AMBV4.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
$CIEL3.SA: possibly delisted; no timezone found
[**********************96%*********************  ]  238 of 248 completed$HGTX3.SA: possibly delisted; no timezone found
[**********************96%*********************  ]  239 of 248 completed$CPLE6.SA: possibly delisted; no timezone found
[**********************97%********************** ]  241 of 248 completed$AEDU3.SA: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)
[*********************100%***********************]  248 of 248 completed

104 Failed downloads:
['RRRP3.SA', 'CESP6.SA', 'NTCO3.SA', 'ELET6.SA', 'ARZZ3.SA', 'BRDT3.SA', 'MILK11.SA', 'ENBR3.SA', 'ECOD3.SA', 'TIET11.SA', 'ESTC3.SA', 'MMXM3.SA', 'GUAR3.SA', 'SMLS3.SA', 'LINX3.SA', 'BIDI11.SA', 'PETZ3.SA', 'ELET3.SA', 'VIVO4.SA', 'WIZS3.SA', 'PARD3.SA', 'GNDI3.SA', 'BRFS3.SA', 'VIVT4.SA', 'CRFB3.SA', 'CCRO3.SA', 'PCAR5.SA', 'BIDI4.SA', 'SULA11.SA', 'PCAR4.SA', 'TRPL4.SA', 'ELPL3.SA', 'EMBR3.SA', 'VVAR3.SA', 'VIIA3.SA', 'AZUL4.SA', 'CNTO3.SA', 'LCAM3.SA', 'MRFG3.SA', 'KROT3.SA', 'ALSC3.SA', 'ELPL6.SA', 'BBRK3.SA', 'SOMA3.SA', 'DTEX3.SA', 'LAME4.SA', 'JBSS3.SA', 'QGEP3.SA', 'IGTA3.SA', 'BTOW3.SA', 'ENAT3.SA', 'TIMP3.SA', 'LAME3.SA', 'MPLU3.SA', 'BPAN4.SA', 'STBP3.SA', 'ALSO3.SA', 'BRML3.SA', 'BKBR3.SA', 'MAGG3.SA', 'GOLL4.SA', 'CIEL3.SA', 'HGTX3.SA', 'CPLE6.SA']: possibly delisted; no timezone found
['BVMF3.SA', 'BRTO4.SA', 'TBLE3.SA', 'AMIL3.SA', 'MNDL4.SA', 'BPNM4.SA', 'SMLE3.SA', 'BRIN3.SA', 'GETI3.SA', 'TCSL4.SA', 'STBP11.SA', 'ARTR3.SA', 'FFTL4.SA', 'TMAR5.SA', 'TNLP3.SA', 'AMBV3.SA', 'GETI4.SA', 'UGPA4.SA', 'CRUZ3.SA', 'KROT11.SA', 'LLXL3.SA', 'BBTG11.SA', 'CTIP3.SA', 'OHLB3.SA', 'RUMO3.SA', 'RDCD3.SA', 'DROG3.SA', 'ALLL3.SA', 'NETC4.SA', 'TNLP4.SA', 'IMCH3.SA', 'TAMM4.SA', 'AGEN11.SA', 'HRTP3.SA', 'SUZB5.SA', 'TLPP4.SA', 'MPXE3.SA', 'BISA3.SA', 'AMBV4.SA', 'AEDU3.SA']: possibly delisted; no price data found  (1d 2010-01-01 -> 2026-01-01)

In [6]:
precos_ajustados = dados_yahoo["Close"]

precos_ajustados.head()

Ticker,ABCB4.SA,ABEV3.SA,AEDU3.SA,AGEN11.SA,ALLL3.SA,ALOS3.SA,ALPA4.SA,ALSC3.SA,ALSO3.SA,ALUP11.SA,...,VIVA3.SA,VIVO4.SA,VIVT3.SA,VIVT4.SA,VLID3.SA,VVAR11.SA,VVAR3.SA,WEGE3.SA,WIZS3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,3.447088,2.942420,NaN,NaN,NaN,NaN,2.031718,NaN,NaN,NaN,...,NaN,NaN,5.334549,NaN,7.787282,NaN,NaN,1.914480,NaN,5.078549
2010-01-05,3.539198,2.959729,NaN,NaN,NaN,NaN,2.038784,NaN,NaN,NaN,...,NaN,NaN,5.314783,NaN,7.779212,NaN,NaN,1.910303,NaN,5.139384
2010-01-06,3.597812,2.989923,NaN,NaN,NaN,NaN,2.033484,NaN,NaN,NaN,...,NaN,NaN,5.224415,NaN,7.807457,NaN,NaN,1.920747,NaN,5.223292
2010-01-07,3.544780,3.003961,NaN,NaN,NaN,NaN,2.054685,NaN,NaN,NaN,...,NaN,NaN,5.224415,NaN,7.827629,NaN,NaN,1.953125,NaN,5.139384
2010-01-08,3.516869,2.998191,NaN,NaN,NaN,NaN,2.075885,NaN,NaN,NaN,...,NaN,NaN,5.220178,NaN,7.989027,NaN,NaN,2.024148,NaN,5.139384

In [7]:
precos_ajustados.columns = precos_ajustados.columns.str.replace(".SA", "", regex=False)

precos_ajustados.head()

Ticker,ABCB4,ABEV3,AEDU3,AGEN11,ALLL3,ALOS3,ALPA4,ALSC3,ALSO3,ALUP11,...,VIVA3,VIVO4,VIVT3,VIVT4,VLID3,VVAR11,VVAR3,WEGE3,WIZS3,YDUQ3
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,3.447088,2.942420,NaN,NaN,NaN,NaN,2.031718,NaN,NaN,NaN,...,NaN,NaN,5.334549,NaN,7.787282,NaN,NaN,1.914480,NaN,5.078549
2010-01-05,3.539198,2.959729,NaN,NaN,NaN,NaN,2.038784,NaN,NaN,NaN,...,NaN,NaN,5.314783,NaN,7.779212,NaN,NaN,1.910303,NaN,5.139384
2010-01-06,3.597812,2.989923,NaN,NaN,NaN,NaN,2.033484,NaN,NaN,NaN,...,NaN,NaN,5.224415,NaN,7.807457,NaN,NaN,1.920747,NaN,5.223292
2010-01-07,3.544780,3.003961,NaN,NaN,NaN,NaN,2.054685,NaN,NaN,NaN,...,NaN,NaN,5.224415,NaN,7.827629,NaN,NaN,1.953125,NaN,5.139384
2010-01-08,3.516869,2.998191,NaN,NaN,NaN,NaN,2.075885,NaN,NaN,NaN,...,NaN,NaN,5.220178,NaN,7.989027,NaN,NaN,2.024148,NaN,5.139384

In [8]:
print(f"Matriz de preços ajustados: {precos_ajustados.shape[0]} datas e {precos_ajustados.shape[1]} ativos")
print(f"Data inicial: {precos_ajustados.index.min()}")
print(f"Data final: {precos_ajustados.index.max()}")

precos_ajustados.iloc[:5, :10]

Matriz de preços ajustados: 4064 datas e 248 ativos
Data inicial: 2010-01-04 00:00:00
Data final: 2025-12-30 00:00:00

Ticker,ABCB4,ABEV3,AEDU3,AGEN11,ALLL3,ALOS3,ALPA4,ALSC3,ALSO3,ALUP11
Date,,,,,,,,,,
2010-01-04,3.447088,2.942420,NaN,NaN,NaN,NaN,2.031718,NaN,NaN,NaN
2010-01-05,3.539198,2.959729,NaN,NaN,NaN,NaN,2.038784,NaN,NaN,NaN
2010-01-06,3.597812,2.989923,NaN,NaN,NaN,NaN,2.033484,NaN,NaN,NaN
2010-01-07,3.544780,3.003961,NaN,NaN,NaN,NaN,2.054685,NaN,NaN,NaN
2010-01-08,3.516869,2.998191,NaN,NaN,NaN,NaN,2.075885,NaN,NaN,NaN

### 1. Conferência dos dados faltantes nos preços ajustados

Após baixar os preços ajustados pelo Yahoo Finance, é necessário verificar a quantidade de dados faltantes por ativo. Essa etapa ajuda a identificar quais tickers possuem histórico incompleto ou não foram encontrados corretamente na base do Yahoo.

A presença de valores ausentes é esperada, pois nem todos os ativos existiam desde 2010 ou possuem histórico completo disponível no Yahoo Finance.

In [9]:
percentual_dados_yahoo = precos_ajustados.notna().mean().sort_values(ascending=False)

percentual_dados_yahoo.head(20)

Ticker
ABCB4    0.977854
ABEV3    0.977854
ALPA4    0.977854
AMAR3    0.977854
AMER3    0.977854
BBAS3    0.977854
BBDC4    0.977854
BBDC3    0.977854
BRAP4    0.977854
BRKM5    0.977854
CMIG3    0.977854
BRSR6    0.977854
BEEF3    0.977854
EGIE3    0.977854
DXCO3    0.977854
DIRR3    0.977854
CYRE3    0.977854
DASA3    0.977854
CSNA3    0.977854
CSMG3    0.977854
dtype: float64

In [10]:
percentual_dados_yahoo.tail(20)

Ticker
RDCD3     0.0
STBP11    0.0
STBP3     0.0
SULA11    0.0
TCSL4     0.0
TBLE3     0.0
SUZB5     0.0
TIET11    0.0
TIMP3     0.0
TLPP4     0.0
TMAR5     0.0
TNLP3     0.0
UGPA4     0.0
TRPL4     0.0
TNLP4     0.0
VIIA3     0.0
VIVO4     0.0
VIVT4     0.0
VVAR3     0.0
WIZS3     0.0
dtype: float64